Repository PrestaShop/gsitemap, pull requests merged in 2024-01, with the labels that each got.

#174 Remove old way of getting product images
  gsitemap.php
Labels: waiting for QA

#173 Re added manufacturers list
  config.xml
  gsitemap.php
  tests/phpstan/phpstan-1.7.1.2.neon
  tests/phpstan/phpstan-1.7.2.5.neon
  tests/phpstan/phpstan-1.7.3.4.neon
  tests/phpstan/phpstan-1.7.4.4.neon
  tests/phpstan/phpstan-1.7.5.1.neon
  tests/phpstan/phpstan-1.7.6.neon
  tests/phpstan/phpstan-1.7.7.neon
  tests/phpstan/phpstan-1.7.8.neon
  upgrade/upgrade-4.4.0.php
Labels: QA ✔️

#175 Add controller for CRON tasks and minor fixes
  controllers/front/cron.php
  controllers/front/index.php
  controllers/index.php
  gsitemap-cron.php
  gsitemap.php
Labels: waiting for author

#176 Release version 4.4.0
  config.xml
  controllers/front/cron.php
  controllers/front/index.php
  controllers/index.php
  gsitemap-cron.php
  gsitemap.php
  tests/phpstan/phpstan-1.7.1.2.neon
  tests/phpstan/phpstan-1.7.2.5.neon
  tests/phpstan/phpstan-1.7.3.4.neon
  tests/phpstan/phpstan-1.7.4.4.neon
  tests/phpstan/phpstan-1.7.5.1.neon
  tests/phpstan/phpstan-1.7.6.neon
  tests/phpstan/phpstan-1.7.7.neon
  tests/phpstan/phpstan-1.7.8.neon
  upgrade/upgrade-4.4.0.php
Labels: QA ✔️

#177 Standardize upgrade files
  upgrade/install-2.2.0.php
Labels: waiting for QA
